/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Classes.DbConnection;
import Classes.User;

import java.sql.*;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;


/**
 *
 * @author padilla
 */
public class LoginFrame extends javax.swing.JFrame {
    MainFrame main ;
    /**
     * Creates new form LoginFrame
     */
    User user;
    Connection conn = null;
    public LoginFrame() {
        conn = DbConnection.dbConnect();
        initComponents();
        init();
    }
    private void logIn(){
        String username = txtUserName.getText();
        String password = txtPassword.getText();
        String sql= "Select * from tbl_users INNER JOIN tbl_userinfo on tbl_userinfo.user_id = tbl_users.user_id where binary username=? and binary pass_word=?";
        try{
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, username);
            pst.setString(2, password);
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()){
                int id = Integer.parseInt(rs.getString("user_id"));
                String firstName = rs.getString("user_firstname");
                String role = rs.getString("user_role");
                String lastName = rs.getString("user_lastname");
                String contact = rs.getString("user_contact");
                String email = rs.getString("user_email");
                 BufferedImage im = ImageIO.read(rs.getBinaryStream("user_image"));
                ImageIcon img = new ImageIcon(im);
                user = new User( id,  firstName,  lastName,  role,  contact,  email,  img);
                
                main = new MainFrame();
                main.setUser(user);
                dispose();
                main.setVisible(true);
                
            }else{
                
                txtUserName.requestFocus();
                
                txtPassword.setText("Password");
                txtPassword.setEchoChar((char)0);
                txtPassword.setForeground(new Color(204,204,204));
               warning("Wrong Username and Password");
            }
            
            
            
            
        }catch(Exception e){
            System.out.println(e);
        }
    }
    
    private void warning(String str){
        lblWarning.setText(str);
        lblWarning.setVisible(true);
    }
    
    private void init(){
        
        lblWarning.setVisible(false);
       
        txtPassword.setEchoChar((char)0);
        txtPassword.setText("Password");
        
        ImageIcon closeIcon = new ImageIcon(this.getClass().getClassLoader().getResource("img/close.png"));
        lblClose.setIcon(closeIcon);
        
        ImageIcon sysLogo = new ImageIcon(this.getClass().getClassLoader().getResource("img/maxiLogo.png"));
        lblSysLogo.setIcon(sysLogo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblWarning = new javax.swing.JLabel();
        lblSysLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUserName.setForeground(new java.awt.Color(204, 204, 204));
        txtUserName.setText("User Name");
        txtUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserNameFocusLost(evt);
            }
        });
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserNameKeyPressed(evt);
            }
        });
        jPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 105, 242, 24));

        txtPassword.setForeground(new java.awt.Color(204, 204, 204));
        txtPassword.setText("Password");
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 168, 242, 26));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Waree", 1, 11)); // NOI18N
        jButton1.setText("Login");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 212, 62, 29));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("URW Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 51, 106, 48));

        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        jPanel1.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 1, 30, 20));

        lblWarning.setBackground(new java.awt.Color(238, 174, 44));
        lblWarning.setForeground(new java.awt.Color(255, 0, 0));
        lblWarning.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 100, 13), 0));
        jPanel1.add(lblWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 253, -1, 44));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 0, 330, 380));
        jPanel3.add(lblSysLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 250, 200));

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Copyrights© 2022");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(txtUserName.getText().length()==0 || txtUserName.getText().equals("User Name") && txtPassword.getText().length()==0 || txtPassword.getText().equals("Password")){
            warning("Input Username and Password");
            txtUserName.requestFocus();
        }else{
            logIn();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserNameFocusGained
        
    }//GEN-LAST:event_txtUserNameFocusGained

    private void txtUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyPressed
       if(txtUserName.getText().equals("User Name")){
            txtUserName.setText("");
            txtUserName.setForeground(Color.BLACK);
        }
       lblWarning.setVisible(false);
    }//GEN-LAST:event_txtUserNameKeyPressed

    private void txtUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserNameFocusLost
       if(txtUserName.getText().equals("")){
            txtUserName.setText("User Name");
            txtUserName.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtUserNameFocusLost

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        if(txtPassword.getText().equals("Password")){
            txtPassword.setText("");
            txtPassword.setEchoChar('•');
            txtPassword.setForeground(Color.BLACK);
        }
        
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            if(txtUserName.getText().length()==0 || txtUserName.getText().equals("User Name") && txtPassword.getText().length()==0 || txtPassword.getText().equals("Password")){
                warning("Input Username and Password");
                txtUserName.requestFocus();
            }else{
                logIn();
            }
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        if(txtPassword.getText().equals("")){
            txtPassword.setText("Password");
            txtPassword.setEchoChar((char)0);
            txtPassword.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        
    }//GEN-LAST:event_txtPasswordFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblSysLogo;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
