/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;


import Classes.DbConnection;
import Classes.LogsClass;
import Classes.User;
import Panels.DashBoard;
import Panels.Inventory;
import Panels.PointOfSales;
import Panels.Reports;
import Panels.Users;
import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.*;
import javax.swing.ImageIcon;


/**
 *
 * @author padilla
 */


public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    DashBoard dashBoard = new DashBoard();;
    Inventory inventory = new Inventory();
    PointOfSales pointOfSales =new PointOfSales() ;
    Reports reports =new Reports();
    Users users= new Users();
    Connection conn = null;
    User user;
    
   
    
    ImageIcon disabledUser = new ImageIcon(this.getClass().getClassLoader().getResource("Icons/manBNW.png"));
    
    public void setUser(User user){
        this.user =user;
       // lblImage.setIcon(user.getImg());
        circularImage();
        lblName.setText(user.getFirstName()+" "+user.getLastName());
        lblRole.setText(user.getRole());
        System.out.println(user.getRole());
         if(user.getRole().equals("User")){
          
            jLabel28.setIcon(disabledUser);
            
        }
      //   System.out.println(user.getId()+" "+user.getFirstName()+" "+user.getLastName()+" "+user.getRole()+" "+user.getEmail()+" "+user.getContact());
    }
    public MainFrame() {
        
        conn = DbConnection.dbConnect();


        this.add(dashBoard);
        this.add(inventory);
        this.add(pointOfSales);
        this.add(reports);
        this.add(users);
       
        initComponents();
        init();
        
        
                         
    }
    
    private void init(){
//        activePanel(menuDashboard);
        showPanel(dashBoard);
        dashBoard.init();
        activePanel_mini(miniMenuDashboard);

        showPanel_mini(dashBoard);
//        sidePanel.hide();
//        x=0;
        
      
                
        
    }
    

    
     
    
    private void circularImage(){
        try{
             
            //ImageIcon i = new ImageIcon(this.getClass().getClassLoader().getResource("img/defaultUser.gif"));
            BufferedImage master = new BufferedImage(user.getImg().getIconWidth(), user.getImg().getIconHeight(), BufferedImage.TYPE_INT_RGB);
            Graphics g = master.createGraphics();
            
            user.getImg().paintIcon(null, g, 0, 0);
           
               
            int diameter = Math.min(master.getWidth(), master.getHeight());
            BufferedImage mask = new BufferedImage(master.getWidth(), master.getHeight(), BufferedImage.TYPE_INT_ARGB);

            Graphics2D g2d = mask.createGraphics();
            applyQualityRenderingHints(g2d);
            g2d.fillOval(0, 0, diameter - 1, diameter - 1);
            g2d.dispose();

            BufferedImage masked = new BufferedImage(diameter, diameter, BufferedImage.TYPE_INT_ARGB);
            g2d = masked.createGraphics();
            applyQualityRenderingHints(g2d);
            int _x = (diameter - master.getWidth()) / 2;
            int y = (diameter - master.getHeight()) / 2;
            g2d.drawImage(master, _x, y, null);
            g2d.setComposite(AlphaComposite.getInstance(AlphaComposite.DST_IN));
            g2d.drawImage(mask, 0, 0, null);
            g2d.dispose();
            
            ImageIcon ii = new ImageIcon(masked);
            Image img = ii.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
                

            lblImage.setIcon(new ImageIcon(img));
        }catch(Exception e){
            System.out.println(e);
        }
        
    }
   


    

       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidePanelMini = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        miniMenuLogout = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        miniMenuDashboard = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        miniMenuPOS = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        miniMeniReport = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        miniMenuInventory = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        miniMenuUsers = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(990, 625));
        setMinimumSize(new java.awt.Dimension(990, 625));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 625));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 625));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanelMini.setBackground(new java.awt.Color(51, 51, 51));
        sidePanelMini.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-hamburger-menu-48.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        sidePanelMini.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 49, -1));

        miniMenuLogout.setBackground(new java.awt.Color(51, 51, 51));
        miniMenuLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniMenuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMenuLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniMenuLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniMenuLogoutMouseExited(evt);
            }
        });
        miniMenuLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logout.png"))); // NOI18N
        miniMenuLogout.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        sidePanelMini.add(miniMenuLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 50, 60));

        miniMenuDashboard.setBackground(new java.awt.Color(51, 51, 51));
        miniMenuDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniMenuDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMenuDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniMenuDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniMenuDashboardMouseExited(evt);
            }
        });
        miniMenuDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/monitor.png"))); // NOI18N
        miniMenuDashboard.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        sidePanelMini.add(miniMenuDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 50, 60));

        miniMenuPOS.setBackground(new java.awt.Color(51, 51, 51));
        miniMenuPOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniMenuPOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMenuPOSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniMenuPOSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniMenuPOSMouseExited(evt);
            }
        });
        miniMenuPOS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-transaction-approved-48.png"))); // NOI18N
        miniMenuPOS.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        sidePanelMini.add(miniMenuPOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 50, 60));

        miniMeniReport.setBackground(new java.awt.Color(51, 51, 51));
        miniMeniReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniMeniReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMeniReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniMeniReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniMeniReportMouseExited(evt);
            }
        });
        miniMeniReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/business-report.png"))); // NOI18N
        miniMeniReport.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        sidePanelMini.add(miniMeniReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 50, 60));

        miniMenuInventory.setBackground(new java.awt.Color(51, 51, 51));
        miniMenuInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniMenuInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMenuInventoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniMenuInventoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniMenuInventoryMouseExited(evt);
            }
        });
        miniMenuInventory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-inventory-67.png"))); // NOI18N
        miniMenuInventory.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        sidePanelMini.add(miniMenuInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 50, 60));

        miniMenuUsers.setBackground(new java.awt.Color(51, 51, 51));
        miniMenuUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniMenuUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMenuUsersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniMenuUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniMenuUsersMouseExited(evt);
            }
        });
        miniMenuUsers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/man.png"))); // NOI18N
        miniMenuUsers.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        sidePanelMini.add(miniMenuUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 50, 60));

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Copyrights 2020");
        sidePanelMini.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 120, -1));

        jPanel1.add(sidePanelMini, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 73, 49, 552));

        lblImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 12, 50, 50));

        lblRole.setFont(new java.awt.Font("Manjari Thin", 1, 14)); // NOI18N
        lblRole.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 100, 20));

        lblName.setFont(new java.awt.Font("Manjari Thin", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 190, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
//        
//        if (x == 0){
//            sidePanel.show();
//            sidePanel.setSize(x,552);
//            Thread th = new Thread(){
//                @Override
//                public void run(){
//                    try{
//                        for(int i=0; i<=x;i++){
//                            Thread.sleep(1);
//                            sidePanel.setSize(i, 552);
//                        }
//                    }catch(Exception e){
//                        JOptionPane.showMessageDialog(null, e);
//                    }
//                }
//                    
//            };th.start();
//           x=210;
//           
//        }
//         jLabel1.show();
//         jLabel2.hide();
//         
//          System.out.println("show "+x);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void miniMenuLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuLogoutMouseEntered
       panelColor(miniMenuLogout);
    }//GEN-LAST:event_miniMenuLogoutMouseEntered

    private void miniMenuLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuLogoutMouseExited
       resetPanelColor(miniMenuLogout);
    }//GEN-LAST:event_miniMenuLogoutMouseExited

    private void miniMenuDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuDashboardMouseEntered
       panelColor( miniMenuDashboard);
    }//GEN-LAST:event_miniMenuDashboardMouseEntered

    private void miniMenuDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuDashboardMouseExited
        resetPanelColor(miniMenuDashboard);
    }//GEN-LAST:event_miniMenuDashboardMouseExited

    private void miniMenuPOSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuPOSMouseEntered
        panelColor( miniMenuPOS);
    }//GEN-LAST:event_miniMenuPOSMouseEntered

    private void miniMenuPOSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuPOSMouseExited
        resetPanelColor(miniMenuPOS);
    }//GEN-LAST:event_miniMenuPOSMouseExited

    private void miniMeniReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMeniReportMouseEntered
        panelColor( miniMeniReport);
    }//GEN-LAST:event_miniMeniReportMouseEntered

    private void miniMeniReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMeniReportMouseExited
       resetPanelColor(miniMeniReport);
    }//GEN-LAST:event_miniMeniReportMouseExited

    private void miniMenuInventoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuInventoryMouseEntered
        panelColor( miniMenuInventory);
    }//GEN-LAST:event_miniMenuInventoryMouseEntered

    private void miniMenuInventoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuInventoryMouseExited
        resetPanelColor(miniMenuInventory);
    }//GEN-LAST:event_miniMenuInventoryMouseExited

    private void miniMenuUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuUsersMouseEntered
        panelColor( miniMenuUsers);
    }//GEN-LAST:event_miniMenuUsersMouseEntered

    private void miniMenuUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuUsersMouseExited
        resetPanelColor(miniMenuUsers);
    }//GEN-LAST:event_miniMenuUsersMouseExited

    private void miniMenuDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuDashboardMouseClicked
       activePanel_mini(miniMenuDashboard);
       showPanel_mini(dashBoard); 
          dashBoard.init();
    }//GEN-LAST:event_miniMenuDashboardMouseClicked

    private void miniMenuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuLogoutMouseClicked
        LoginFrame login = new LoginFrame();
          int reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to Log out?","Log out", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                user = null;
        login.show();
        dispose();
            }
        
    }//GEN-LAST:event_miniMenuLogoutMouseClicked

    private void miniMenuPOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuPOSMouseClicked
        activePanel_mini(miniMenuPOS);
       showPanel_mini(pointOfSales); 
       pointOfSales.setUserInstance(user);
    }//GEN-LAST:event_miniMenuPOSMouseClicked

    private void miniMeniReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMeniReportMouseClicked
      
        activePanel_mini(miniMeniReport);
        showPanel_mini(reports); 
        reports.init();
    }//GEN-LAST:event_miniMeniReportMouseClicked

    private void miniMenuInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuInventoryMouseClicked
       activePanel_mini(miniMenuInventory);
       showPanel_mini(inventory); 
       inventory.setUser(user);
    }//GEN-LAST:event_miniMenuInventoryMouseClicked

    private void miniMenuUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuUsersMouseClicked

       
       if (user.getRole().equals("Admin")) {

              activePanel_mini(miniMenuUsers);
       showPanel_mini(users); 
        }

    }//GEN-LAST:event_miniMenuUsersMouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        labelColor(jLabel2);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
       resetLabelColor(jLabel2);
    }//GEN-LAST:event_jLabel2MouseExited

    private void usersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseEntered
      
    }//GEN-LAST:event_usersMouseEntered

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
     
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRole;
    private javax.swing.JPanel miniMeniReport;
    private javax.swing.JPanel miniMenuDashboard;
    private javax.swing.JPanel miniMenuInventory;
    private javax.swing.JPanel miniMenuLogout;
    private javax.swing.JPanel miniMenuPOS;
    private javax.swing.JPanel miniMenuUsers;
    private javax.swing.JPanel sidePanelMini;
    // End of variables declaration//GEN-END:variables
    private void labelColor(JLabel label){
        label.setBackground(new Color(51,70,70));
    }
    private void resetLabelColor(JLabel label){
        label.setBackground(new Color(51,51,51));
    }
    
    private void panelColor(JPanel panel){
        if(panel.getBackground().getRGB()!=-6715513){
            panel.setBackground(new Color(51,70,70));
        }
        
    }
    private void resetPanelColor(JPanel panel){
        if(panel.getBackground().getRGB()!=-6715513){
             panel.setBackground(new Color(51,51,51));
        }
       
    }
    
    
    
    private void activePanel(JPanel panel){
        Color original = new Color(51,51,51);
        Color active = new Color(153,135,135);
        
//        menuDashboard.setBackground(original);
//        menuInventory.setBackground(original);
//        menuPOS.setBackground(original);
//        menuReport.setBackground(original);
//        menuUsers.setBackground(original);
//        
        miniMenuDashboard.setBackground(original);
        miniMenuInventory.setBackground(original);
        miniMenuPOS.setBackground(original);
        miniMeniReport.setBackground(original);
        miniMenuUsers.setBackground(original);
        
        
        panel.setBackground(active);
    }
    
    private void activePanel_mini(JPanel panel){
        Color original = new Color(51,51,51);
        Color active = new Color(153,135,135);
        
      
        
        miniMenuDashboard.setBackground(original);
        miniMenuInventory.setBackground(original);
        miniMenuPOS.setBackground(original);
        miniMeniReport.setBackground(original);
        miniMenuUsers.setBackground(original);
        
        
        panel.setBackground(active);
    }
    
    
    private void showPanel(JPanel panel){
        dashBoard.hide();
   
         reports.hide();
        pointOfSales.hide();
        users.hide();
        inventory.hide();

        panel.setLocation(50,73);
        panel.setSize(950, 560);
        panel.show();
       
    }
    
        public static void applyQualityRenderingHints(Graphics2D g2d) {

        g2d.setRenderingHint(RenderingHints.KEY_ALPHA_INTERPOLATION, RenderingHints.VALUE_ALPHA_INTERPOLATION_QUALITY);
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2d.setRenderingHint(RenderingHints.KEY_COLOR_RENDERING, RenderingHints.VALUE_COLOR_RENDER_QUALITY);
        g2d.setRenderingHint(RenderingHints.KEY_DITHERING, RenderingHints.VALUE_DITHER_ENABLE);
        g2d.setRenderingHint(RenderingHints.KEY_FRACTIONALMETRICS, RenderingHints.VALUE_FRACTIONALMETRICS_ON);
        g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        g2d.setRenderingHint(RenderingHints.KEY_STROKE_CONTROL, RenderingHints.VALUE_STROKE_PURE);

    }
    
     private void showPanel_mini(JPanel panel){
        
        dashBoard.hide();
        reports.hide();
        pointOfSales.hide();
        users.hide();
        inventory.hide();
        
       
//        sidePanel.hide();
        panel.setLocation(49,73);
        panel.setSize(950, 560);
        panel.show();
        

    }
}
