/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;


import Classes.DbConnection;
import Classes.User;
import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.*;
import javax.swing.ImageIcon;


/**
 *
 * @author padilla
 */


public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    Connection conn = null;
    User user;
    
    public void setUser(User user){
        this.user =user;
       // lblImage.setIcon(user.getImg());
        circularImage();
        lblName.setText(user.getFirstName()+" "+user.getLastName());
        lblRole.setText(user.getRole());
      //   System.out.println(user.getId()+" "+user.getFirstName()+" "+user.getLastName()+" "+user.getRole()+" "+user.getEmail()+" "+user.getContact());
    }
    public MainFrame() {
        
        conn = DbConnection.dbConnect();
        initComponents();
        init();
        
        
                         
    }
    
    private void init(){
        activePanel(menuDashboard);
        showPanel(dashBoard);
        activePanel_mini(miniMenuDashboard);

        showPanel_mini(dashBoard);
        sidePanel.hide();
        x=0;
                
        
    }
    

    
     
    
    private void circularImage(){
        try{
             
            //ImageIcon i = new ImageIcon(this.getClass().getClassLoader().getResource("img/defaultUser.gif"));
            BufferedImage master = new BufferedImage(user.getImg().getIconWidth(), user.getImg().getIconHeight(), BufferedImage.TYPE_INT_RGB);
            Graphics g = master.createGraphics();
            
            user.getImg().paintIcon(null, g, 0, 0);
           
               
            int diameter = Math.min(master.getWidth(), master.getHeight());
            BufferedImage mask = new BufferedImage(master.getWidth(), master.getHeight(), BufferedImage.TYPE_INT_ARGB);

            Graphics2D g2d = mask.createGraphics();
            applyQualityRenderingHints(g2d);
            g2d.fillOval(0, 0, diameter - 1, diameter - 1);
            g2d.dispose();

            BufferedImage masked = new BufferedImage(diameter, diameter, BufferedImage.TYPE_INT_ARGB);
            g2d = masked.createGraphics();
            applyQualityRenderingHints(g2d);
            int _x = (diameter - master.getWidth()) / 2;
            int y = (diameter - master.getHeight()) / 2;
            g2d.drawImage(master, _x, y, null);
            g2d.setComposite(AlphaComposite.getInstance(AlphaComposite.DST_IN));
            g2d.drawImage(mask, 0, 0, null);
            g2d.dispose();
            
            ImageIcon ii = new ImageIcon(masked);
            Image img = ii.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
                

            lblImage.setIcon(new ImageIcon(img));
        }catch(Exception e){
            System.out.println(e);
        }
        
    }
   


    

       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        menuLogout = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        menuDashboard = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        menuPOS = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        menuReport = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        menuInventory = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        menuUsers = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        sidePanelMini = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        miniMenuLogout = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        miniMenuDashboard = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        miniMenuPOS = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        miniMeniReport = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        miniMenuInventory = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        miniMenuUsers = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        users = new Panels.Users();
        reports = new Panels.Reports();
        pointOfSales = new Panels.PointOfSales();
        inventory = new Panels.Inventory();
        dashBoard = new Panels.DashBoard();
        lblImage = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 625));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 625));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 625));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(51, 51, 51));
        sidePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sidePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sidePanelMouseExited(evt);
            }
        });
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuLogout.setBackground(new java.awt.Color(51, 51, 51));
        menuLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuLogoutMouseExited(evt);
            }
        });
        menuLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logout.png"))); // NOI18N
        menuLogout.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel12.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Logout");
        menuLogout.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 140, 20));

        sidePanel.add(menuLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 210, 60));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-hamburger-menu-48.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        sidePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 49, -1));

        menuDashboard.setBackground(new java.awt.Color(51, 51, 51));
        menuDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuDashboardMouseExited(evt);
            }
        });
        menuDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/monitor.png"))); // NOI18N
        menuDashboard.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dashboard");
        menuDashboard.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 140, 20));

        sidePanel.add(menuDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 210, 60));

        menuPOS.setBackground(new java.awt.Color(51, 51, 51));
        menuPOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuPOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPOSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuPOSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuPOSMouseExited(evt);
            }
        });
        menuPOS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-transaction-approved-48.png"))); // NOI18N
        menuPOS.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Point of Sales");
        menuPOS.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 140, 20));

        sidePanel.add(menuPOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 210, 60));

        menuReport.setBackground(new java.awt.Color(51, 51, 51));
        menuReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuReportMouseExited(evt);
            }
        });
        menuReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/business-report.png"))); // NOI18N
        menuReport.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Report");
        menuReport.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 140, 20));

        sidePanel.add(menuReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 210, 60));

        menuInventory.setBackground(new java.awt.Color(51, 51, 51));
        menuInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuInventoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuInventoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuInventoryMouseExited(evt);
            }
        });
        menuInventory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-inventory-67.png"))); // NOI18N
        menuInventory.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Inventory");
        menuInventory.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 140, 20));

        sidePanel.add(menuInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 210, 60));

        menuUsers.setBackground(new java.awt.Color(51, 51, 51));
        menuUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuUsersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuUsersMouseExited(evt);
            }
        });
        menuUsers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/man.png"))); // NOI18N
        menuUsers.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel14.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Users");
        menuUsers.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 140, 20));

        sidePanel.add(menuUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 210, 60));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Copyrights 2020");
        sidePanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 120, -1));

        jPanel1.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 73, 210, 552));

        sidePanelMini.setBackground(new java.awt.Color(51, 51, 51));
        sidePanelMini.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-hamburger-menu-48.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        sidePanelMini.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 49, -1));

        miniMenuLogout.setBackground(new java.awt.Color(51, 51, 51));
        miniMenuLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniMenuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMenuLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniMenuLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniMenuLogoutMouseExited(evt);
            }
        });
        miniMenuLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logout.png"))); // NOI18N
        miniMenuLogout.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        sidePanelMini.add(miniMenuLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 50, 60));

        miniMenuDashboard.setBackground(new java.awt.Color(51, 51, 51));
        miniMenuDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniMenuDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMenuDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniMenuDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniMenuDashboardMouseExited(evt);
            }
        });
        miniMenuDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/monitor.png"))); // NOI18N
        miniMenuDashboard.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        sidePanelMini.add(miniMenuDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 50, 60));

        miniMenuPOS.setBackground(new java.awt.Color(51, 51, 51));
        miniMenuPOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniMenuPOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMenuPOSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniMenuPOSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniMenuPOSMouseExited(evt);
            }
        });
        miniMenuPOS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-transaction-approved-48.png"))); // NOI18N
        miniMenuPOS.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        sidePanelMini.add(miniMenuPOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 50, 60));

        miniMeniReport.setBackground(new java.awt.Color(51, 51, 51));
        miniMeniReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniMeniReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMeniReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniMeniReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniMeniReportMouseExited(evt);
            }
        });
        miniMeniReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/business-report.png"))); // NOI18N
        miniMeniReport.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        sidePanelMini.add(miniMeniReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 50, 60));

        miniMenuInventory.setBackground(new java.awt.Color(51, 51, 51));
        miniMenuInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniMenuInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMenuInventoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniMenuInventoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniMenuInventoryMouseExited(evt);
            }
        });
        miniMenuInventory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-inventory-67.png"))); // NOI18N
        miniMenuInventory.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        sidePanelMini.add(miniMenuInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 50, 60));

        miniMenuUsers.setBackground(new java.awt.Color(51, 51, 51));
        miniMenuUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniMenuUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMenuUsersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniMenuUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniMenuUsersMouseExited(evt);
            }
        });
        miniMenuUsers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/man.png"))); // NOI18N
        miniMenuUsers.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        sidePanelMini.add(miniMenuUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 50, 60));

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Copyrights 2020");
        sidePanelMini.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 120, -1));

        jPanel1.add(sidePanelMini, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 73, 49, 552));

        users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usersMouseEntered(evt);
            }
        });
        jPanel1.add(users, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 73, -1, -1));
        jPanel1.add(reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 73, -1, -1));
        jPanel1.add(pointOfSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 73, -1, -1));
        jPanel1.add(inventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 73, -1, -1));
        jPanel1.add(dashBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 73, -1, -1));

        lblImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 12, 50, 50));

        lblRole.setFont(new java.awt.Font("Manjari Thin", 1, 14)); // NOI18N
        lblRole.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 100, 20));

        lblName.setFont(new java.awt.Font("Manjari Thin", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 190, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    int x = 210;
    
    public void hideSidePanel(){
           if (x == 210){
            sidePanel.setSize(210,552);
            Thread th = new Thread(){
                @Override
                public void run(){
                    try{
                        for(int i=210; i>=0;i--){
                            Thread.sleep(1);
                            sidePanel.setSize(i, 552);
                        }
                        sidePanel.hide();
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
                    
           
            };th.start();
           x=0;
          
        }
        jLabel1.hide();   
        jLabel2.show();
          
        System.out.println("hide "+x);
    }
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if (x == 210){
            
            sidePanel.setSize(210,552);
            Thread th = new Thread(){
                @Override
                public void run(){
                    try{
                        for(int i=210; i>=0;i--){
                            Thread.sleep(1);
                            sidePanel.setSize(i, 552);
                        }
                        sidePanel.hide();
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
                    
            };th.start();
           x=0;
            
        }
        jLabel1.hide();   
        jLabel2.show();
        
        System.out.println("hide "+x);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        if (x == 0){
            sidePanel.show();
            sidePanel.setSize(x,552);
            Thread th = new Thread(){
                @Override
                public void run(){
                    try{
                        for(int i=0; i<=x;i++){
                            Thread.sleep(1);
                            sidePanel.setSize(i, 552);
                        }
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
                    
            };th.start();
           x=210;
           
        }
         jLabel1.show();
         jLabel2.hide();
         
          System.out.println("show "+x);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
       labelColor(jLabel1);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
         resetLabelColor(jLabel1);
    }//GEN-LAST:event_jLabel1MouseExited

    private void menuDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDashboardMouseEntered
        panelColor(menuDashboard);
    }//GEN-LAST:event_menuDashboardMouseEntered

    private void menuDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDashboardMouseExited
        resetPanelColor(menuDashboard);
    }//GEN-LAST:event_menuDashboardMouseExited

    private void menuPOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPOSMouseClicked
        activePanel(menuPOS);
        showPanel(pointOfSales);
    }//GEN-LAST:event_menuPOSMouseClicked

    private void menuPOSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPOSMouseEntered
        panelColor(menuPOS);
    }//GEN-LAST:event_menuPOSMouseEntered

    private void menuPOSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPOSMouseExited
       resetPanelColor(menuPOS);
    }//GEN-LAST:event_menuPOSMouseExited

    private void menuReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportMouseClicked
        activePanel(menuReport);
        showPanel(reports);
    }//GEN-LAST:event_menuReportMouseClicked

    private void menuReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportMouseEntered
         panelColor(menuReport);
    }//GEN-LAST:event_menuReportMouseEntered

    private void menuReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportMouseExited
        resetPanelColor(menuReport);
    }//GEN-LAST:event_menuReportMouseExited

    private void menuInventoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuInventoryMouseEntered
        panelColor(menuInventory);
    }//GEN-LAST:event_menuInventoryMouseEntered

    private void menuInventoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuInventoryMouseExited
        resetPanelColor(menuInventory);
    }//GEN-LAST:event_menuInventoryMouseExited

    private void menuUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUsersMouseEntered
       panelColor(menuUsers);
    }//GEN-LAST:event_menuUsersMouseEntered

    private void menuUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUsersMouseExited
        resetPanelColor(menuUsers);
          if(menuUsers.getBackground().getRGB()==-6715513){
              hideSidePanel();
        }
    }//GEN-LAST:event_menuUsersMouseExited

    private void menuLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseEntered
        panelColor(menuLogout);
    }//GEN-LAST:event_menuLogoutMouseEntered

    private void menuLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseExited
       resetPanelColor(menuLogout);
    }//GEN-LAST:event_menuLogoutMouseExited

    private void miniMenuLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuLogoutMouseEntered
       panelColor(miniMenuLogout);
    }//GEN-LAST:event_miniMenuLogoutMouseEntered

    private void miniMenuLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuLogoutMouseExited
       resetPanelColor(miniMenuLogout);
    }//GEN-LAST:event_miniMenuLogoutMouseExited

    private void miniMenuDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuDashboardMouseEntered
       panelColor( miniMenuDashboard);
    }//GEN-LAST:event_miniMenuDashboardMouseEntered

    private void miniMenuDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuDashboardMouseExited
        resetPanelColor(miniMenuDashboard);
    }//GEN-LAST:event_miniMenuDashboardMouseExited

    private void miniMenuPOSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuPOSMouseEntered
        panelColor( miniMenuPOS);
    }//GEN-LAST:event_miniMenuPOSMouseEntered

    private void miniMenuPOSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuPOSMouseExited
        resetPanelColor(miniMenuPOS);
    }//GEN-LAST:event_miniMenuPOSMouseExited

    private void miniMeniReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMeniReportMouseEntered
        panelColor( miniMeniReport);
    }//GEN-LAST:event_miniMeniReportMouseEntered

    private void miniMeniReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMeniReportMouseExited
       resetPanelColor(miniMeniReport);
    }//GEN-LAST:event_miniMeniReportMouseExited

    private void miniMenuInventoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuInventoryMouseEntered
        panelColor( miniMenuInventory);
    }//GEN-LAST:event_miniMenuInventoryMouseEntered

    private void miniMenuInventoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuInventoryMouseExited
        resetPanelColor(miniMenuInventory);
    }//GEN-LAST:event_miniMenuInventoryMouseExited

    private void miniMenuUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuUsersMouseEntered
        panelColor( miniMenuUsers);
    }//GEN-LAST:event_miniMenuUsersMouseEntered

    private void miniMenuUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuUsersMouseExited
        resetPanelColor(miniMenuUsers);
    }//GEN-LAST:event_miniMenuUsersMouseExited

    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
       
    }//GEN-LAST:event_menuLogoutMouseClicked

    private void menuUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUsersMouseClicked
        activePanel(menuUsers);
        
        showPanel(users);
       
        
       
      
    }//GEN-LAST:event_menuUsersMouseClicked

    private void menuInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuInventoryMouseClicked
        activePanel(menuInventory);
        showPanel(inventory);
    }//GEN-LAST:event_menuInventoryMouseClicked

    private void menuDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDashboardMouseClicked
        activePanel(menuDashboard);
        showPanel(dashBoard);
    }//GEN-LAST:event_menuDashboardMouseClicked

    private void miniMenuDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuDashboardMouseClicked
       activePanel_mini(miniMenuDashboard);
       showPanel_mini(dashBoard); 
         
    }//GEN-LAST:event_miniMenuDashboardMouseClicked

    private void miniMenuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuLogoutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_miniMenuLogoutMouseClicked

    private void miniMenuPOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuPOSMouseClicked
        activePanel_mini(miniMenuPOS);
       showPanel_mini(pointOfSales); 
    }//GEN-LAST:event_miniMenuPOSMouseClicked

    private void miniMeniReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMeniReportMouseClicked
       activePanel_mini(miniMeniReport);
       showPanel_mini(reports); 
    }//GEN-LAST:event_miniMeniReportMouseClicked

    private void miniMenuInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuInventoryMouseClicked
       activePanel_mini(miniMenuInventory);
       showPanel_mini(inventory); 
    }//GEN-LAST:event_miniMenuInventoryMouseClicked

    private void miniMenuUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMenuUsersMouseClicked
        activePanel_mini(miniMenuUsers);
       showPanel_mini(users); 
    }//GEN-LAST:event_miniMenuUsersMouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        labelColor(jLabel2);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
       resetLabelColor(jLabel2);
    }//GEN-LAST:event_jLabel2MouseExited

    private void sidePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidePanelMouseExited
       

        
        
           
        

    }//GEN-LAST:event_sidePanelMouseExited

    private void sidePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidePanelMouseEntered
      
    }//GEN-LAST:event_sidePanelMouseEntered

    private void usersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseEntered
      
    }//GEN-LAST:event_usersMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Panels.DashBoard dashBoard;
    private Panels.Inventory inventory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRole;
    private javax.swing.JPanel menuDashboard;
    private javax.swing.JPanel menuInventory;
    private javax.swing.JPanel menuLogout;
    private javax.swing.JPanel menuPOS;
    private javax.swing.JPanel menuReport;
    private javax.swing.JPanel menuUsers;
    private javax.swing.JPanel miniMeniReport;
    private javax.swing.JPanel miniMenuDashboard;
    private javax.swing.JPanel miniMenuInventory;
    private javax.swing.JPanel miniMenuLogout;
    private javax.swing.JPanel miniMenuPOS;
    private javax.swing.JPanel miniMenuUsers;
    private Panels.PointOfSales pointOfSales;
    private Panels.Reports reports;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel sidePanelMini;
    private Panels.Users users;
    // End of variables declaration//GEN-END:variables
    private void labelColor(JLabel label){
        label.setBackground(new Color(51,70,70));
    }
    private void resetLabelColor(JLabel label){
        label.setBackground(new Color(51,51,51));
    }
    
    private void panelColor(JPanel panel){
        if(panel.getBackground().getRGB()!=-6715513){
            panel.setBackground(new Color(51,70,70));
        }
        
    }
    private void resetPanelColor(JPanel panel){
        if(panel.getBackground().getRGB()!=-6715513){
             panel.setBackground(new Color(51,51,51));
        }
       
    }
    
    
    
    private void activePanel(JPanel panel){
        Color original = new Color(51,51,51);
        Color active = new Color(153,135,135);
        
        menuDashboard.setBackground(original);
        menuInventory.setBackground(original);
        menuPOS.setBackground(original);
        menuReport.setBackground(original);
        menuUsers.setBackground(original);
        
        miniMenuDashboard.setBackground(original);
        miniMenuInventory.setBackground(original);
        miniMenuPOS.setBackground(original);
        miniMeniReport.setBackground(original);
        miniMenuUsers.setBackground(original);
        
        
        panel.setBackground(active);
    }
    
    private void activePanel_mini(JPanel panel){
        Color original = new Color(51,51,51);
        Color active = new Color(153,135,135);
        
      
        
        miniMenuDashboard.setBackground(original);
        miniMenuInventory.setBackground(original);
        miniMenuPOS.setBackground(original);
        miniMeniReport.setBackground(original);
        miniMenuUsers.setBackground(original);
        
        
        panel.setBackground(active);
    }
    
    
    private void showPanel(JPanel panel){
        dashBoard.hide();
        reports.hide();
        pointOfSales.hide();
        users.hide();
        inventory.hide();
        
        panel.show();
       
    }
    
        public static void applyQualityRenderingHints(Graphics2D g2d) {

        g2d.setRenderingHint(RenderingHints.KEY_ALPHA_INTERPOLATION, RenderingHints.VALUE_ALPHA_INTERPOLATION_QUALITY);
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2d.setRenderingHint(RenderingHints.KEY_COLOR_RENDERING, RenderingHints.VALUE_COLOR_RENDER_QUALITY);
        g2d.setRenderingHint(RenderingHints.KEY_DITHERING, RenderingHints.VALUE_DITHER_ENABLE);
        g2d.setRenderingHint(RenderingHints.KEY_FRACTIONALMETRICS, RenderingHints.VALUE_FRACTIONALMETRICS_ON);
        g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        g2d.setRenderingHint(RenderingHints.KEY_STROKE_CONTROL, RenderingHints.VALUE_STROKE_PURE);

    }
    
     private void showPanel_mini(JPanel panel){
        
        dashBoard.hide();
        reports.hide();
        pointOfSales.hide();
        users.hide();
        inventory.hide();
        
       
        sidePanel.hide();
        panel.show();

    }
}
