/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panels.mini;

import Panels.PointOfSales;
import java.awt.Color;

/**
 *
 * @author padilla
 */
public class CartItem extends javax.swing.JPanel {

    /**
     * Creates new form CartItem
     */
    String name;
    public int index;
    private double total;
    private PointOfSales pos;
    private String qty;
    public CartItem() {
        initComponents();
    }
    
    public void setItem(String name, String qty, String price){
        float pricef =Float.parseFloat(price);
        float total = Float.parseFloat(qty)* pricef;
        this.name =name;
        this.total=total;
        
        this.qty =qty;
        lblName.setText("<html><p>"+name+"</p></html>");
        lblQty.setText(qty);
        lblPrice.setText("P"+price);
        lblTotal.setText(String.valueOf(total));
    }
    
    public double getTotal(){
        return total;
    }
    
    public void setInstance(PointOfSales pos) {
        this.pos = pos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotal = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblQty = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        jPanelDelete = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(388, 37));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotal.setFont(new java.awt.Font("AnjaliOldLipi", 0, 14)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("Total");
        lblTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(153, 153, 153)));
        add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 70, 40));

        lblName.setFont(new java.awt.Font("URW Gothic L", 1, 12)); // NOI18N
        lblName.setText("Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 170, 40));

        lblQty.setFont(new java.awt.Font("AnjaliOldLipi", 0, 14)); // NOI18N
        lblQty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQty.setText("qty");
        lblQty.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(153, 153, 153)));
        add(lblQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 70, 40));

        lblPrice.setFont(new java.awt.Font("AnjaliOldLipi", 0, 14)); // NOI18N
        lblPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrice.setText("price");
        lblPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(153, 153, 153)));
        add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 70, 40));

        jPanelDelete.setBackground(new java.awt.Color(204, 0, 0));
        jPanelDelete.setForeground(new java.awt.Color(51, 153, 0));
        jPanelDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelDeleteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelDeleteMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanelDeleteMouseReleased(evt);
            }
        });
        jPanelDelete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Umpush", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete-24.png"))); // NOI18N
        jLabel7.setText("+");
        jPanelDelete.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 19, 20));

        add(jPanelDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 7, 25, 25));
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDeleteMouseClicked
        int stock =  Integer.parseInt(PointOfSales.cartItem.get(index).getItemStock());
        int qty = Integer.parseInt(this.qty);
        int total = stock + qty;
        PointOfSales.cartItem.get(index).setStock(String.valueOf(total));
        PointOfSales.cartItem.remove(index);
         
        for(Item i :PointOfSales.cartItem ){
            System.out.print(i.getItemName()+" ");
        }
        System.out.println("");
        pos.loadCart();
    }//GEN-LAST:event_jPanelDeleteMouseClicked

    private void jPanelDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDeleteMouseEntered
        jPanelDelete.setBackground(new Color(255, 39, 9));
    }//GEN-LAST:event_jPanelDeleteMouseEntered

    private void jPanelDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDeleteMouseExited
        jPanelDelete.setBackground(new Color(204, 0, 0));
    }//GEN-LAST:event_jPanelDeleteMouseExited

    private void jPanelDeleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDeleteMousePressed
        jPanelDelete.setBackground(new Color(204, 0, 0));
    }//GEN-LAST:event_jPanelDeleteMousePressed

    private void jPanelDeleteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDeleteMouseReleased
        jPanelDelete.setBackground(new Color(255, 39, 9));
    }//GEN-LAST:event_jPanelDeleteMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelDelete;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables
}
