/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panels.mini;

import Frames.mini.AddQty;
import Panels.PointOfSales;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author padilla
 */


public class Item extends javax.swing.JPanel {

    /**
     * Creates new form Item
     */
    private String name;
    private String price;
    private String stock;
    private String qty;
    
    
    private boolean enable =true;
    
    private PointOfSales pos;
    
    private String id;

    public Item() {
        initComponents();
    }
    public void enableItem(boolean enabled){
        this.enable =enabled;
        if(!enable){
          lblName.setForeground(Color.RED);
          lblStocks.setForeground(Color.RED);
        }
        
    }
    
    public boolean isItemEnabled(){
        return enable;
    }
    
    public String getId(){
        return id;
    }
    public String getItemName(){
        return this.name;
    }
    public String getItemPrice(){
        return this.price;
    }
    public String getItemStock(){
        return this.stock;
    }
    
    public void setId(String id){
        this.id =id;
    }
    
    public void setQty(String qty){
        this.qty =qty;
    }
    
     public void setStock(String stock){
        this.stock = stock;
        if(this.stock.equals("0")){
            enable = false;
            lblName.setForeground(Color.RED);
          lblStocks.setForeground(Color.RED);
        }else{
              enable = true;
            lblName.setForeground(Color.black);
          lblStocks.setForeground(Color.black);
        }
        lblStocks.setText("Stocks: "+stock);
    }
    public String getQty(){
        return qty;
    }
    
    public void setItem(String name, String price, String stock){
        
       
        lblName.setText(name);
        lblPrice.setText("Price: P"+price);
        lblStocks.setText("Stocks: "+stock);
        this.name=name;
        this.price=price;
        this.stock =stock;
       
        
    }
    
    
    public void setInstance(PointOfSales pos){
        this.pos=pos;
    }
    
    public void setImage(ImageIcon icon){
        lblImage.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrice = new javax.swing.JLabel();
        lblStocks = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(137, 162, 201));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(155, 214));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPrice.setFont(new java.awt.Font("AnjaliOldLipi", 0, 11)); // NOI18N
        lblPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrice.setText("Price");
        add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 130, -1));

        lblStocks.setFont(new java.awt.Font("AnjaliOldLipi", 0, 11)); // NOI18N
        lblStocks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStocks.setText("Stocks");
        add(lblStocks, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, -1));

        lblName.setFont(new java.awt.Font("AnjaliOldLipi", 1, 11)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, -1));

        lblImage.setBackground(new java.awt.Color(153, 153, 153));
        lblImage.setOpaque(true);
        add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 140, 140));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        this.setBackground(Color.gray);
        if (enable) {
            AddQty add = new AddQty();
            add.open(this, pos);
            add.show();
            // PointOfSales.cartItem.add(this);

            //pos.loadCart();
           //pos.highlightItemMouseClick(this);

        }
        
    }//GEN-LAST:event_formMouseClicked

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
       
    }//GEN-LAST:event_formFocusLost

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
       this.setBackground(new Color(137,162,201));
    }//GEN-LAST:event_formMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblStocks;
    // End of variables declaration//GEN-END:variables
}
