/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PrintPages;

import Classes.PrintComponent;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author padilla
 */
public class FramePrintReport extends javax.swing.JFrame {

    /**
     * Creates new form FramePrintReport
     */
    public FramePrintReport() {
        initComponents();
        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

     public void setReciept(String receiptNum) {
        lblReceiptNum.setText(receiptNum);
    }

    public void setDate(String date) {
        lblDate.setText(date);
    }

    public void setCount(int count) {
        lblItemCount.setText(String.valueOf(count));
    }

    public void setTotal(float x) {
        lblTotal.setText("TOTAL: P" + String.valueOf(x));
    }

    public void populateList(DefaultListModel itemList) {
        lstItems.setModel(itemList);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        PanelReport = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTransNum3 = new javax.swing.JLabel();
        lblDate1 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstItems = new javax.swing.JList<>();
        lblTotal = new javax.swing.JLabel();
        lblItemCount = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblReceiptNum = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("AnjaliOldLipi", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Print ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 6, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/printer-32.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 26, 26));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 70, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelReport.setBackground(new java.awt.Color(255, 255, 255));
        PanelReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MAXILIFE LOGO TRANSPARENT (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PanelReport.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 70));

        lblTransNum3.setFont(new java.awt.Font("AnjaliOldLipi", 1, 14)); // NOI18N
        lblTransNum3.setText("Reciept No.");
        PanelReport.add(lblTransNum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 100, 20));

        lblDate1.setFont(new java.awt.Font("AnjaliOldLipi", 1, 14)); // NOI18N
        lblDate1.setText("Date:");
        PanelReport.add(lblDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 100, 20));

        label1.setFont(new java.awt.Font("AnjaliOldLipi", 1, 14)); // NOI18N
        label1.setText("Item(s)");
        PanelReport.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 100, 20));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setOpaque(false);

        lstItems.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        lstItems.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstItems);

        PanelReport.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 380, 200));

        lblTotal.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PanelReport.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 110, 20));

        lblItemCount.setFont(new java.awt.Font("AnjaliOldLipi", 1, 14)); // NOI18N
        PanelReport.add(lblItemCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 160, 20));

        lblDate.setFont(new java.awt.Font("AnjaliOldLipi", 1, 14)); // NOI18N
        PanelReport.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 160, 20));

        lblReceiptNum.setFont(new java.awt.Font("AnjaliOldLipi", 1, 14)); // NOI18N
        PanelReport.add(lblReceiptNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 160, 20));

        jLabel2.setFont(new java.awt.Font("Nimbus Sans Narrow", 1, 27)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html><p>Maxilife Maternity Lying-in and Multispecialty Clinic Co.</p></html>");
        PanelReport.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 340, 70));

        jLabel3.setFont(new java.awt.Font("Noto Sans Mono CJK TC", 0, 14)); // NOI18N
        jLabel3.setText("Email: maxilife_clinic2018@yahoo.com");
        PanelReport.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 310, 20));

        jLabel4.setFont(new java.awt.Font("Noto Sans Mono CJK TC", 0, 14)); // NOI18N
        jLabel4.setText("<html><p>Jose Abad Santos Avenue, San Fernando Sur,         Cabiao, Philippines</p></html>");
        PanelReport.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 310, 40));

        jLabel5.setFont(new java.awt.Font("Noto Sans Mono CJK TC", 0, 14)); // NOI18N
        jLabel5.setText("Tel No.: 0933 818 5130");
        PanelReport.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 310, 20));

        jPanel1.add(PanelReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 500, 560));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -30, 570, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        PrintComponent print = new PrintComponent();
       
        print.printComponent(PanelReport);
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

        dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrintReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrintReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrintReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrintReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrintReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDate1;
    private javax.swing.JLabel lblItemCount;
    private javax.swing.JLabel lblReceiptNum;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTransNum3;
    private javax.swing.JList<String> lstItems;
    // End of variables declaration//GEN-END:variables
}
