/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames.mini;

import Classes.DbConnection;
import Classes.LogsClass;
import Classes.User;
import Panels.Inventory;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;    
import javax.swing.JOptionPane;

/**
 *
 * @author padilla
 */
public class RestrockFrame extends javax.swing.JFrame {

    /**
     * Creates new form RestrockFrame
     */
    Connection conn = null;
    private String title;
    private String name;
    private String id;
    private String stock;
    User user;    
    
    LogsClass log = new LogsClass();
    
    
    Inventory i;

    public RestrockFrame() {
         
        conn = DbConnection.dbConnect();
        initComponents();
        panelAdd.setBackground(Color.GRAY);
    }
    
    public void setInstance(Inventory i){
        this.i = i;
        
    }
    

   
    
    
    
    
    
    public void setDetails(String title, String id, String stock, String name, User user){
        this.title =title;
        this.id = id;
        this.stock = stock;
        this.name = name;
        this.user = user;
    }
    public void loadDefault(){
       
        lblTitle.setText(title);
        lblCurrent.setText(stock);
    }
    
   
    
    private void updateStocks(String value){
        String sql = "Update tbl_iteminfo set item_stock ='"+value+"' where item_code ='"+id+"'";
        try{
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
        }catch(Exception e ){
            System.out.println("error update "+e);
        }
    }
    
    private void insertStocks(String qty, String date, String batch_code, String item_code){
        System.out.println(batch_code.length());
        String sql = "insert into tbl_itemstock(qty, date, batch_code, item_code) values(?,?,?,?)";
        try{
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, qty);
            pst.setString(2, date);
            pst.setString(3, batch_code);
            pst.setString(4, item_code);
            pst.execute();
        }catch(Exception e ){
            System.out.println("error update "+e);
        }
    }
    
    
    
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtStocks = new javax.swing.JTextField();
        panelAdd = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblCurrent = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 155, 29));

        label1.setBackground(new java.awt.Color(51, 51, 51));
        label1.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Add New");
        label1.setOpaque(true);
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 80, 25));

        lblTotal.setBackground(new java.awt.Color(255, 255, 255));
        lblTotal.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        lblTotal.setOpaque(true);
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 80, 25));

        txtStocks.setBorder(new javax.swing.border.MatteBorder(null));
        txtStocks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStocksKeyReleased(evt);
            }
        });
        jPanel1.add(txtStocks, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 80, 25));

        panelAdd.setBackground(new java.awt.Color(5, 192, 12));
        panelAdd.setForeground(new java.awt.Color(51, 153, 0));
        panelAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAddMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelAddMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelAddMouseReleased(evt);
            }
        });
        panelAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Umpush", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("+");
        panelAdd.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 19, 20));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("AnjaliOldLipi", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Add");
        panelAdd.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 5, 40, 18));

        jPanel1.add(panelAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 60, 25));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 80, 30));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, 25));

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Current");
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, 25));

        lblCurrent.setBackground(new java.awt.Color(255, 255, 255));
        lblCurrent.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        lblCurrent.setOpaque(true);
        jPanel1.add(lblCurrent, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 80, 25));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panelAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddMouseClicked
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MM/dd/YYYY");  
        DateTimeFormatter dtf2 = DateTimeFormatter.ofPattern("MMdd-YY");  
         
        LocalDateTime now = LocalDateTime.now();
        String dateCode = dtf2.format(now);
        System.out.println(dateCode);
        String batch_code = generateBatchCode(dateCode);
        String date = dtf.format(now);
       // System.out.println(dtf.format(now));  
        String qty = txtStocks.getText();
        
        
        
        
        int reply = JOptionPane.showConfirmDialog(null, "Adding "+qty+" to "+name, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
             updateStocks(lblTotal.getText());
             insertStocks(qty, date, batch_code, id);
             JOptionPane.showMessageDialog(null, qty+"pcs of "+name+" was Added to Inventory");
            log.insertToLog(user.getUserName(), "Added "+qty+"pcs of stock on "+name);
           
          //  i.hide();
            i.displayAllItem("Select * from tbl_items inner join tbl_iteminfo on tbl_items.item_code = tbl_iteminfo.item_code");
           
             dispose();
        }
    }//GEN-LAST:event_panelAddMouseClicked

    private void panelAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddMouseEntered
        panelAdd.setBackground(new Color(5, 255, 0));
    }//GEN-LAST:event_panelAddMouseEntered

    private void panelAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddMouseExited
        panelAdd.setBackground(new Color(5, 192, 12));
    }//GEN-LAST:event_panelAddMouseExited

    private void panelAddMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddMousePressed
        //jPanelAdd.setBackground(new Color(5,101,3));
        panelAdd.setBackground(new Color(5, 192, 12));
    }//GEN-LAST:event_panelAddMousePressed

    private void panelAddMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddMouseReleased
        panelAdd.setBackground(new Color(5, 255, 0));
    }//GEN-LAST:event_panelAddMouseReleased

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

        dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void txtStocksKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStocksKeyReleased
        txtStocks.setHorizontalAlignment(txtStocks.RIGHT);
        String str = txtStocks.getText();
        
        //str = str.replaceAll("[^\\d]", "");
        str = str.replaceAll( "[^0-9]", "");
        
       
        
        txtStocks.setText(str);
        if(str.length()==0){
            panelAdd.setBackground(Color.GRAY);
        }else{
          int total =computeTotal(lblCurrent.getText(), txtStocks.getText());
          lblTotal.setText(String.valueOf(total));
           panelAdd.setBackground(new Color(5, 255, 0));
        }
     
    }//GEN-LAST:event_txtStocksKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestrockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestrockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestrockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestrockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestrockFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel lblCurrent;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelAdd;
    private javax.swing.JTextField txtStocks;
    // End of variables declaration//GEN-END:variables
    private String generateBatchCode(String dateCode){
        return "MD"+dateCode;
    }
    private int computeTotal(String current, String incoming){
        return Integer.parseInt(current)+ Integer.parseInt(incoming);
    }
}
